version: '3.2'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=t_clone_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'

  app:
    build:
      context: app
    links:
      - postgres:postgres
    stop_signal: SIGKILL
    environment:
      DEBUG: False
      POSTGRES_DB: t_clone_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      DATABASE_PORT: 5432
    expose:
      - "8000"
    depends_on:
      - postgres
    ports:
      - '8000:8000'

  nginx:
    build:
      context: nginx
    ports:
      - '80:80'
    depends_on:
      - app
      - postgres
