"""update tweets table - column content renamed to tweet_data

Revision ID: f3eea0f6394a
Revises: f6c26d4a705d
Create Date: 2024-03-18 22:28:27.686405

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3eea0f6394a"
down_revision: Union[str, None] = "f6c26d4a705d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tweets", sa.Column("tweet_data", sa.Text(), nullable=False))
    op.drop_column("tweets", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tweets", sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.drop_column("tweets", "tweet_data")
    # ### end Alembic commands ###
