"""added ondelete CASCADE to tweet relation mixin

Revision ID: 7102d4226058
Revises: f3eea0f6394a
Create Date: 2024-03-21 21:05:54.484301

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7102d4226058"
down_revision: Union[str, None] = "f3eea0f6394a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("likes_tweet_id_fkey", "likes", type_="foreignkey")
    op.create_foreign_key(
        None, "likes", "tweets", ["tweet_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "likes", type_="foreignkey")
    op.create_foreign_key("likes_tweet_id_fkey", "likes", "tweets", ["tweet_id"], ["id"])
    # ### end Alembic commands ###
