"""added cascade=delete-orphan to Tweet.likes

Revision ID: c3106a0f3417
Revises: 7102d4226058
Create Date: 2024-03-21 21:18:12.078324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3106a0f3417"
down_revision: Union[str, None] = "7102d4226058"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("likes_tweet_id_fkey", "likes", type_="foreignkey")
    op.create_foreign_key(None, "likes", "tweets", ["tweet_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "likes", type_="foreignkey")
    op.create_foreign_key(
        "likes_tweet_id_fkey",
        "likes",
        "tweets",
        ["tweet_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
